Fix `TypeError: inst._eth.resolveAddress is not a function` error. Fetch and display token symbol. Correctly handle the `provider` option. No longer exit with failure if user says no. Verify transfer with event logs. Update ERC20 ABI to be more complete. Update dependencies.